Repository DG266/ReFair-App, pull requests merged in 2024-09, with the labels that each got.

#11 test(refair-server): add unit tests
  refair-server/requirements.txt
  refair-server/test_REFAIR.py
  refair-server/test_app.py
Labels: testing

#12 test(refair-server): add integration tests
  refair-server/test_integration_REFAIR.py
  refair-server/test_integration_app.py
Labels: testing

#13 test: add system tests
  system_tests/data/analyze_tc_1/oracle.json
  system_tests/data/analyze_tc_1/stories.xlsx
  system_tests/data/load_tc_10_(1.1.1.2.0.2.0.2.0.1.0.)/stories.xlsx
  system_tests/data/load_tc_11_(1.1.2.2.2.2.2.2.2.3.1.)/stories.xlsx
  system_tests/data/load_tc_12_(1.1.2.2.2.2.2.2.2.3.2.)/stories.xlsx
  system_tests/data/load_tc_13_(1.1.1.2.0.2.0.2.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_14_(1.1.1.2.0.2.0.2.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_15_(1.1.1.2.0.2.0.3.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_16_(1.1.1.2.0.2.0.3.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_17_(1.1.2.2.1.2.0.2.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_18_(1.1.2.2.1.2.0.2.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_19_(1.1.2.2.1.2.0.3.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_1_(2.1.1.2.0.2.0.2.0.3.0)/This file name should not be accepted.xlsx
  system_tests/data/load_tc_20_(1.1.2.2.1.2.0.3.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_21_(1.1.2.2.2.2.1.2.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_22_(1.1.2.2.2.2.1.2.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_23_(1.1.2.2.2.2.1.3.0.2.0.)/stories.xlsx
  system_tests/data/load_tc_24_(1.1.2.2.2.2.1.3.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_25_(1.1.2.2.2.2.2.2.2.2.3.)/stories.xlsx
  system_tests/data/load_tc_26_(1.1.2.2.2.2.2.2.2.3.3.)/stories.xlsx
  system_tests/data/load_tc_27_(1.1.2.2.2.2.2.3.2.2.3.)/stories.xlsx
  system_tests/data/load_tc_28_(1.1.2.2.2.2.2.3.2.3.3.)/stories.xlsx
  system_tests/data/load_tc_2_(1.2.0.0.0.0.0.0.0.0.0)/stories.txt
  system_tests/data/load_tc_3_(1.1.1.1.0.0.0.0.0.0.0)/stories.xlsx
  system_tests/data/load_tc_4_(1.1.1.3.0.2.0.2.0.3.0)/stories.xlsx
  system_tests/data/load_tc_5_(1.1.2.2.3.2.1.2.0.3.0)/stories.xlsx
  system_tests/data/load_tc_6_(1.1.1.2.0.1.0.0.0.0.0)/stories.xlsx
  system_tests/data/load_tc_7_(1.1.1.2.0.2.0.1.0.0.0)/stories.xlsx
  system_tests/data/load_tc_8_(1.1.1.2.0.2.0.4.0.3.0.)/stories.xlsx
  system_tests/data/load_tc_9_(1.1.2.2.2.2.2.2.1.3.0.)/stories.xlsx
  system_tests/data/report_single_us_tc_1/report-As a radiologist, I want to use the ID3 algorithm to develop decision tree models for diagnosing and predicting medical conditions based on various medic.json
  system_tests/data/report_tc_1/oracle.json
  system_tests/data/report_tc_1/report.json
  system_tests/data/report_tc_2/oracle.json
  system_tests/data/report_tc_2/report.json
  system_tests/requirements.txt
  system_tests/tests/__init__.py
  system_tests/tests/conftest.py
  system_tests/tests/test_analyze.py
  system_tests/tests/test_load.py
  system_tests/tests/test_report.py
Labels: testing

#20 feat(web-app): Add analysis of a single User Story
  refair-client/src/components/ButtonComponent.vue
  refair-client/src/components/refair.vue
Labels: enhancement

#21 Iges/cr3 single user story
  refair-client/src/components/refair.vue
Labels: enhancement

#22 style(web-app): improve web app's UI
  .gitignore
  .idea/.gitignore
  .idea/ReFair-App.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  refair-client/index.html
  refair-client/package-lock.json
  refair-client/package.json
  refair-client/src/assets/base.css
  refair-client/src/assets/main.css
  refair-client/src/assets/style.css
  refair-client/src/components/ChapterButton.vue
  refair-client/src/components/ChapterTitle.vue
  refair-client/src/components/ParagraphTitle.vue
  refair-client/src/components/SelectButton.vue
  refair-client/src/components/SidebarLinkComponent.vue
  refair-client/src/components/refair.vue
  refair-client/src/main.js
  system_tests/data/report_single_us_tc_1/report-As a radiologist, I want to use the ID3 algorithm to develop decision tree models for diagnosing and predicting medical conditions based on var.json
  system_tests/data/report_tc_2/report.json
  system_tests/tests/__pycache__/__init__.cpython-312.pyc
  system_tests/tests/__pycache__/conftest.cpython-312-pytest-8.3.3.pyc
  system_tests/tests/__pycache__/test_pagination.cpython-312-pytest-8.3.3.pyc
  system_tests/tests/__pycache__/test_report.cpython-312-pytest-8.3.3.pyc
  system_tests/tests/conftest.py
  system_tests/tests/test_analyze.py
  system_tests/tests/test_load.py
  system_tests/tests/test_pagination.py
  system_tests/tests/test_report.py
  system_tests/tests/test_single_us.py
Labels: enhancement

#23 feat: Add desktop app
  .gitignore
  desktop_app/colors.py
  desktop_app/components/__init__.py
  desktop_app/components/custom_messagebox.py
  desktop_app/components/user_story_canvas.py
  desktop_app/domain_utils.py
  desktop_app/icons/analytics-outline.png
  desktop_app/icons/bill_invoice_shop_icon.ico
  desktop_app/icons/cloud-download-outline.png
  desktop_app/icons/cloud-upload-outline.png
  desktop_app/icons/code-download-outline.png
  desktop_app/icons/document-attach-outline.png
  desktop_app/icons/right_arrow_icon.ico
  desktop_app/icons/right_arrow_icon.png
  desktop_app/index.py
  node_modules/.package-lock.json
  node_modules/tkinter/README.md
  node_modules/tkinter/package.json
  package-lock.json
  package.json
  system_tests/data/desktop_download_all/desktop_app_results.json
  system_tests/data/desktop_download_all/oracle.json
  system_tests/data/desktop_single_us/desktop_app_single_us.json
  system_tests/data/desktop_single_us/oracle.json
  system_tests/tests/conftest.py
  system_tests/tests/test_desktop_app.py
Labels: enhancement

#24 Iges/cr4 refactoring
  refair-client/src/assets/style.css
  refair-client/src/components/refair.vue
  refair-server/REFAIR.py
  refair-server/app.py
  refair-server/refair_app.py
  refair-server/test_app.py
  refair-server/test_integration_REFAIR.py
Labels: documentation

#25 docs: add documentation
  IGES_Documentation/10_Final_Report.docx.pdf
  IGES_Documentation/1_Report.docx.pdf
  IGES_Documentation/2_Pre-Modification_System_Testing.docx.pdf
  IGES_Documentation/3_Test_Incident_Report (Pre-Modifications).docx.pdf
  IGES_Documentation/4_Master_Test_Plan.docx.pdf
  IGES_Documentation/5_User_Scenario.docx.pdf
  IGES_Documentation/6_Users_Results.docx.pdf
  IGES_Documentation/7_Impact_Analysis.docx.pdf
  IGES_Documentation/8_Modifications_and_Regression_Testing.docx.pdf
  IGES_Documentation/9_Test_Incident_Report (Post-Modifications).docx.pdf
Labels: documentation
